/*
 * API Gateway Service
 *
 * API Gateway Microservice for the Giò system.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"encoding/json"
	"gio-api-gateway/pkg/logging"
	"gio-api-gateway/pkg/model"
	"github.com/gorilla/handlers"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      []string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func errorHandler(w http.ResponseWriter, status int, message string) {
	r := model.ApiResponse{Code: status, Message: message}
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(r); err != nil {
		log.Println(err)
	}
}

func NewRouter() *http.Handler {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = logging.Logger(handler, route.Name)

		router.
			Methods(route.Method...).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	corsHandler := handlers.CORS(
		handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"}),
		handlers.AllowedOrigins([]string{"*"}),
		handlers.AllowedMethods([]string{"GET", "HEAD", "POST", "PUT", "OPTIONS"}),
	)(router)

	return &corsHandler
}

var routes = Routes{
	// Rooms

	Route{
		"GetRooms",
		[]string{http.MethodGet},
		"/rooms",
		GetRooms,
	},

	Route{
		"GetRoomById",
		[]string{http.MethodGet},
		"/rooms/{roomId}",
		GetRoomById,
	},

	// Devices

	Route{
		"GetDevices",
		[]string{http.MethodGet},
		"/rooms/{roomId}/devices",
		GetDevices,
	},

	Route{
		"GetDeviceById",
		[]string{http.MethodGet},
		"/rooms/{roomId}/devices/{deviceId}",
		GetDeviceById,
	},

	Route{
		"GetDeviceReadings",
		[]string{http.MethodGet},
		"/rooms/{roomId}/devices/{deviceId}/readings",
		GetDeviceReadings,
	},

	Route{
		"TriggerDeviceAction",
		[]string{http.MethodPost},
		"/rooms/{roomId}/devices/{deviceId}/actions/{actionName}",
		TriggerDeviceAction,
	},
}
