/*
 * API Gateway Service
 *
 * API Gateway Microservice for the Giò system.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ApiResponse struct {
	Code    int32  `json:"code,omitempty"`
	Type_   string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
}
