/*
 * API Gateway Service
 *
 * API Gateway Microservice for the Giò system.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

import (
	"encoding/json"
	"fmt"
)

type Device struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Mac  string `json:"mac"`
	Room int    `json:"room"`
}

func (i *Device) String() string {
	b, err := json.Marshal(i)
	if err != nil {
		panic(err)
	}
	return string(b)
}

func (i *Device) Validate() (bool, error) {
	if i.ID <= 0 {
		return false, fmt.Errorf("invalid id")
	}

	if i.Name == "" {
		return false, fmt.Errorf("invalid name")
	}

	if i.Mac == "" {
		return false, fmt.Errorf("invalid mac")
	}

	if i.Room <= 0 {
		return false, fmt.Errorf("invalid room")
	}

	return true, nil
}

type Reading struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
	Unit  string `json:"unit"`
}
