/*
 * API Gateway Service
 *
 * API Gateway Microservice for the Giò system.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"

	"github.com/a-liut/gio-api-gateway-ms/src/api"
)

func main() {
	var port int
	flag.IntVar(&port, "port", 8080, "port to be used")

	flag.Parse()

	log.Printf("Server started on port %d", port)

	router := api.NewRouter()

	p := fmt.Sprintf(":%d", port)

	log.Fatal(http.ListenAndServe(p, router))
}
